import type { ChatMessage, Conversation } from "@/lib/types";

export const CURRENT_USER = {
  name: "Sneha",
  initials: "S",
};

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: "rahul",
    kind: "direct",
    name: "Rahul",
    initials: "R",
    accent: "#3a76f0",
    preview: "Hey Sneha, are you free today?",
    timestamp: "2:42 PM",
    unread: 2,
    online: true,
    typing: true,
  },
  {
    id: "priya",
    kind: "direct",
    name: "Priya",
    initials: "P",
    accent: "#0f9d58",
    preview: "See you tomorrow!",
    timestamp: "1:18 PM",
    unread: 0,
    online: false,
    lastSeen: "last seen today at 1:20 PM",
  },
  {
    id: "project-team",
    kind: "group",
    name: "Project Team",
    initials: "PT",
    accent: "#7c4dff",
    preview: "Amit: Meeting at 6 PM",
    timestamp: "11:05 AM",
    unread: 1,
    memberCount: 4,
  },
  {
    id: "weekend-plans",
    kind: "group",
    name: "Weekend Plans",
    initials: "WP",
    accent: "#e67e22",
    preview: "Neha: What time are we leaving?",
    timestamp: "Yesterday",
    unread: 0,
    memberCount: 3,
  },
];

export const INITIAL_MESSAGES: ChatMessage[] = [
  {
    id: "m1",
    conversationId: "rahul",
    senderId: null,
    fromMe: false,
    content: "Hey Sneha!",
    timestamp: "2:41 PM",
  },
  {
    id: "m2",
    conversationId: "rahul",
    senderId: null,
    fromMe: false,
    content: "Are you free today?",
    timestamp: "2:42 PM",
  },
  {
    id: "m3",
    conversationId: "priya",
    senderId: null,
    fromMe: true,
    content: "I'll bring the notes.",
    timestamp: "1:15 PM",
    status: "read",
  },
  {
    id: "m4",
    conversationId: "priya",
    senderId: null,
    fromMe: false,
    content: "See you tomorrow!",
    timestamp: "1:18 PM",
  },
  {
    id: "m5",
    conversationId: "project-team",
    senderId: null,
    fromMe: false,
    content: "Can everyone join the sync?",
    timestamp: "10:58 AM",
  },
  {
    id: "m6",
    conversationId: "project-team",
    senderId: null,
    fromMe: true,
    content: "I'll be there.",
    timestamp: "11:01 AM",
    status: "delivered",
  },
  {
    id: "m7",
    conversationId: "project-team",
    senderId: null,
    fromMe: false,
    content: "Amit: Meeting at 6 PM",
    timestamp: "11:05 AM",
  },
  {
    id: "m8",
    conversationId: "weekend-plans",
    senderId: null,
    fromMe: false,
    content: "Neha: What time are we leaving?",
    timestamp: "Yesterday",
  },
  {
    id: "m9",
    conversationId: "weekend-plans",
    senderId: null,
    fromMe: true,
    content: "Let's do 5 PM.",
    timestamp: "Yesterday",
    status: "sent",
  },
];
